import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Valkirias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="!scroll-smooth">
      <body>
        {children}
      </body>
    </html>
  );
}
